### ISSUE TITLE
Sort by time recent first

### ISSUE THREAD

**Issue by chalkup** [StreetHub/kue-ui#10]
Is there an option to sort the pages with the most recent jobs first?

**Comment by arnaudbenard** [comment]
Not right now but it looks like the JSON API has an order param: https://github.com/LearnBoost/kue/blob/master/lib/http/index.js#L54 . I will implement that feature in the next version. I will keep you in the loop.

**Comment by arnaudbenard** [comment]
Apparently you can only order by id and it doesn't work as expected See https://github.com/Automattic/kue/issues/33 . Still I've implemented it in the new version because it's part of the other ui.

**Comment by tjsail33** [comment]
Very interesting, thanks for the update. Seems counterintuitive that sorting numerically doesn't work properly. Like are they doing string comparisons instead of parsing the int and then performing the comparison? It's just weird.
