### ISSUE TITLE
Live updating on interval?

### ISSUE THREAD

**Issue by bradvogel** [StreetHub/kue-ui#11]
Is there a simple way to make this UI update on an interval like the built-in Kue front-end does?

**Comment by arnaudbenard** [comment]
I have the implementation in the code https://github.com/StreetHub/kue-ui/blob/master/lib/client/app/controllers/application.js#L12 but it's currently commented out.

The api could look like this. I will notify you when I push this update. :)
```js
ui.setup({
    apiURL: '/api',
    baseURL: '/kue',
    updateInterval: 5 // in seconds
});
```

**Comment by arnaudbenard** [comment]
It's in the new version `0.1.0`!
```ui.setup({
    apiURL: '/api', // IMPORTANT: specify the api url
    baseURL: '/kue', // IMPORTANT: specify the base url
    updateInterval: 5000 // Optional: Fetches new data every 5000 ms
});```

Thank you very much for the feedback

**Comment by bradvogel** [comment]
Thanks! BTW, your changelog has 1.1.0 but it should be 0.1.0.

**Comment by arnaudbenard** [comment]
Thanks! :+1:
