### ISSUE TITLE
how to decrease the polling rate on server and customize ui (add progress column )

### ISSUE THREAD

**Issue by nishasingla1224** [StreetHub/kue-ui#14]
I made some changes in templates/components/jobs-table.hbs but my changes didn't reflect.

**Comment by arnaudbenard** [comment]
You can change the polling rate with the `updateInterval` variable, you have an example here: https://github.com/StreetHub/kue-ui/#mount-with-express-and-kue

If you want to change the template, you will need to build it with `grunt build`. https://github.com/StreetHub/kue-ui/#development

**Comment by nishasingla1224** [comment]
Getting error 
Warning:
 Command failed: /bin/sh: 1: ember: not found
 Use --force to continue.

Though I installed ember

**Comment by arnaudbenard** [comment]
You need to install ember-cli 
```
npm install -g ember-cli
```

Let me know if that helped.

**Comment by nishasingla1224** [comment]
I feel there is as issue of client-8c7289da0516184b40368ac92939e974.js

**Comment by nishasingla1224** [comment]
I did same but getting error again 
Cannot find module 'ember-cli/lib/broccoli/ember-app'

**Comment by arnaudbenard** [comment]
You need to install all the modules in the client.
```
cd lib/client
bower install
npm install
```

**Comment by nishasingla1224** [comment]
@arnaudbenard : thanks man but need one more help.
After running grunt build , I started my app and now I am getting some errors like 

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/kue/assets/vendor.css 
http://localhost:3000/kue/assets/client.css
http://localhost:3000/kue/assets/vendor.js
http://localhost:3000/kue/assets/client.js

**Comment by nishasingla1224** [comment]
@arnaudbenard ..thanks a lot :)

**Comment by arnaudbenard** [comment]
No worries, I would love to see what you come up with. :+1:
